### ISSUE TITLE
pypi install

### ISSUE THREAD

**Issue by jordandekraker** [SNG-Newy/eigenstrapping#8]
Hi,

Eigenstrapping is working great using git clone + local pip install, but when i try to install it from pypi i get an error message:
```
>>> import eigenstrapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export03/data/opt/venv/lib/python3.9/site-packages/eigenstrapping/__init__.py", line 1, in <module>
    from .base import (SurfaceEigenstrapping, VolumetricEigenstrapping,
  File "/export03/data/opt/venv/lib/python3.9/site-packages/eigenstrapping/base.py", line 7, in <module>
    from .utils import (
  File "/export03/data/opt/venv/lib/python3.9/site-packages/eigenstrapping/utils.py", line 2, in <module>
    from . import spatial, parutils, stats
  File "/export03/data/opt/venv/lib/python3.9/site-packages/eigenstrapping/stats.py", line 7, in <module>
    from neuromaps import compare_images
ImportError: cannot import name 'compare_images' from 'neuromaps' (/export03/data/opt/venv/lib/python3.9/site-packages/neuromaps/__init__.py)
```

I'd like to package eigenstrapping as a dependency in my own software, [HippoMaps](https://github.com/jordandekraker/hippomaps), but I cannot publish my software to pypi with a dependency that is a git clone. If you could, please publish a new pypi release when you get the chance (even if the code will still be updated with new releases in the future). 
Thanks!

**Comment by nikitas-k** [comment]
Thanks Jordan, please test this out!

**Comment by jordandekraker** [comment]
Working perfectly now, thank you!
